### ISSUE TITLE
Exception on owncloud 10.2.0.5

### ISSUE THREAD

**Issue by grandbyblos** [alfredbuehler/bookmarks#9] opened 2019-06-04 12:34 UTC
Hi.

I just tried to see my bookmark list, on owncloud 10.2.0.5

Everytime I have an exception : Call to undefined function OCP

**Operating system**:  Ubuntu Xenial (16.04 LTS)

**Web server:**: Apache

**Owncloud version:** 10.2.0.5

**Bookmarks version:** 0.10.5

Thank you

**Comment by kaklakariada** [comment] 2019-06-12 17:57
I get the same error in ownCloud 10.2.0 (stable) and Bookmarks 0.10.5.
The complete error message is `Call to undefined function OCP\\\\image_path()`

**Comment by alfredbuehler** [comment] 2019-06-13 06:18
Yes, I know. 

In ownCloud 10.2 they removed some API functions that were used by bookmarks app. I think, according SemVer, no API should be removed within minor version steps. Nevertheless they did it. 

But the issue is fixed in 1cc79ed71f5769565aa4fa8f25374146fc142e8d. I'll create a new release ASAP.

**Comment by grandbyblos** [comment] 2019-06-13 12:39
Oh, I understand!

Thank you for fixing it, I will wait for the update on the market then.

Have a nice day

**Comment by limburgher** [comment] 2019-06-20 15:04
Thanks! I applied the patch manually and it seems good!

**Comment by limburgher** [comment] 2019-06-20 15:11
For the web at least, anyway. I can't seem to connect with the owncloud bookmarks app, but I'm not sure if this is related.

**Comment by ho4ho** [comment] 2019-07-21 12:25
>  I think, according SemVer, no API should be removed within minor version steps. Nevertheless they did it.

https://github.com/owncloud/core/pull/34927 by 10.2.0 break other apps :-/

https://github.com/Yetangitu/owncloud-apps/issues/119, https://github.com/owncloud/core/pull/34927#issuecomment-511320081

**Comment by alfredbuehler** [comment] 2019-08-04 15:27
Solved by v0.10.6

**Closed by alfredbuehler** 2019-08-04 15:27 UTC

**Comment by limburgher** [comment] 2019-08-05 13:30
Confirmed, thank you!

**Comment by alfredbuehler** [comment] 2019-08-05 14:03
Thank you for your patience, @limburgher.
